### ISSUE TITLE
Use of multiple yubikeys

### ISSUE THREAD

**Issue by fgoe** [northox/roundcube-yubikey-plugin#10]
Hi there,

is it possible to implement the use of multiple yubikeys?
At the moment there is just one field for the yubikey ID.
Other tools like Lastpass got 5 to 10 fields to use multiple yubikeys with one account.

That would be a nice feature.

Greets

**Comment by northox** [comment]
I believe it shouldn't be too complex to implement but I don't have any cycles right now. I'll take a look at it on a rainy day.

For the time being, feel free to submit a patch.

**Comment by matleses** [comment]
Hi, if you want, I implemented this feature : https://github.com/matleses/roundcube-yubikey-plugin

**Comment by fgoe** [comment]
Great. Just tested it, seems to work fine. Thanks!

**Comment by northox** [comment]
Thanks! Please submit a pull request and link it to this issue # and I'll merge it after review.

**Comment by northox** [comment]
Closed by #15.
