### ISSUE TITLE
fgets(): SSL operation failed with code 5

### ISSUE THREAD

**Issue by ra1nb0w** [northox/roundcube-yubikey-plugin#11]
after activation and user settings, i receive the following error during login (from php-errors.log and using yubikey)

[14-Dec-2015 22:52:04 Europe/Rome] PHP Warning:  fgets(): SSL operation failed with code 5. OpenSSL Error messages:
error:02001002:system library:fopen:No such file or directory  
error:2006D080:BIO routines:BIO_new_file:no such file
error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib
error:02001002:system library:fopen:No such file or directory
error:2006D080:BIO routines:BIO_new_file:no such file
error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib
error:02001002:system library:fopen:No such file or directory
error:2006D080:BIO routines:BIO_new_file:no such file
error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib
error:02001002:system library:fopen:No such file or directory
error:2006D080:BIO routines:BIO_new_file:no such file
error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib
error:02001002:system library:fopen:No such file or directory
error:2006D080:BIO routines:BIO_new_file:no such file
error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system l in /web/webmail/program/lib/Roundcube/rcube_imap_generic.php on line 198

some ideas about the source of this error?

roundcube version 1.1.3
roundcube-yubikey-plugin: git

thanks

**Comment by northox** [comment]
It seems like your openssl setup (used to validate Yubikey's servers) isn't setup properly. Which OS is this? Any chroot? Version of php?

**Comment by ra1nb0w** [comment]
right deduction but unfortunately I have tried the sample in Yubico.php and works flawless.
Anyway chroot with php-fpm 5.6

**Comment by ra1nb0w** [comment]
strange behavior; it doesn't find the cert file when with other applications like imap works correctly. sorry for the noise and thanks for the answer. have a nice day.
