### ISSUE TITLE
not working with rouncube 1.1.4

### ISSUE THREAD

**Issue by hgue** [northox/roundcube-yubikey-plugin#13]
Hello,
the plugin seems to do nothing with roundcube version 1.1.4. The plugin does not show up on the about page of roundcube. I followed the install guide closely.
Any ideas?

**Comment by northox** [comment]
Hello, I'm currently not running 1.1.4 so I'll upgrade, test and get back to you. In the mean time, anything showing up in the logs? Any other clue you could give me?

**Comment by hgue** [comment]
I have investigated the php log files, but no hints here, sorry... Any
ideas where to get more information that might help you? 

Am 2016-04-04 01:24, schrieb Danny Fullerton:

> Hello, I'm currently not running 1.1.4 so I'll upgrade, test and get back to you. In the mean time, anything showing up in the logs? Any other clue you could give me? 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub [1]
 

Links:
------
[1]
https://github.com/northox/roundcube-yubikey-plugin/issues/13#issuecomment-205075951

**Comment by northox** [comment]
It's working for me. Can you tell me more about your setup? If you used a package to install roundcube, you might not be looking at the proper log file, e.g. debian roundcube's logs are in `/var/log/roundcube/errors`. Please double check that.

**Comment by hgue** [comment]
Hello Danny,
ok, seems to work now. There was an error message in the Roundcube log
file saying it can't load the plugin. I have extracted the plugin in the
folder "roundcube-yubikey-plugin" (name of your github project) and not
as you describe in your installation guide to "yubikey-authentication".
The plugin loader assumes that the plugin's foldername has to match the
filename of the php-file inside (yubikey-authentication.php). Maybe you
should make this pitfall a little bit more clear in your readme file to
help others. 

Thank you!
Heiko 

Am 2016-04-05 02:47, schrieb Danny Fullerton:

> It's working for me. Can you tell me more about your setup? If you used a package to install roundcube, you might not be looking at the proper log file, e.g. debian roundcube's logs are in /var/log/roundcube/errors. Please double check that. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub [1]
 

Links:
------
[1]
https://github.com/northox/roundcube-yubikey-plugin/issues/13#issuecomment-205563056

**Comment by northox** [comment]
Will do. Thanks!
