### ISSUE TITLE
Install instructions not clear enough

### ISSUE THREAD

**Issue by hollaho** [northox/roundcube-yubikey-plugin#14]
The directory name of the plugin must be not "e.g." yubikey_authentication, but **exactly** this. Otherwise, if you e.g. use yubikey as directory name and plugin name, then this error occurs:

PHP Error: Failed to load plugin file /xxx/plugins/yubikey/yubikey.php in /dxxx/roundcube/program/lib/Roundcube/rcube_plugin_api.php on line 198 (GET /mail/)

**Comment by northox** [comment]
Actually, the Readme says it need to be named the same: the directory and within the config. 

Please proposed changes (or send a pull request).

**Comment by hollaho** [comment]
It is just for clarification, as the current wording

"Install the code in the plugin directory (i.e. roundcube/plugins/yubikey_authentication/)."

is misleading. i.e. means for example. I first named it /yubikey and it did not work. But the name has to be exacly "yubikey_authentication" and nothing else.

Therefore I suggest using

"1. Install the code in the plugin directory and name it **exactly** yubikey_authentication (roundcube/plugins/yubikey_authentication/)"

**Comment by northox** [comment]
Thanks!
