### ISSUE TITLE
roundcube 1.2.3 yubikey-plugin is not appearing in "Settings/Server Settings" menu:

### ISSUE THREAD

**Issue by mindas22** [northox/roundcube-yubikey-plugin#22]
Hi, I did git clone to the plugins folder, renamed as per description, 
`roundcubemail/plugins/yubikey_authentication/`

edited config files API keys and 

`$config['plugins'] = array('managesieve', 'password', 'enigma', 'yubikey_authentication');`

`$rcmail_config['yubikey_api_id']  = 'my-Api-id';
$rcmail_config['yubikey_api_key'] = 'my-API-secret';`

But it does not appear in "Settings/Server Settings" menu. 

What could be wrong, where to look?

**Comment by mindas22** [comment]
It the logs: 

`roundcube: PHP Error: Failed to load plugin file /opt/www/roundcubemail/plugins/yubikey_authentication/yubikey_authentication.php in /opt/www/roundcubemail-1.1.1/program/lib/Roundcube/rcube_plugin_api.php on line 173 (GET /mail/?_task=logout&_token=***)`

**Comment by northox** [comment]
Any errors in the logs?

**Comment by northox** [comment]
If you try to access this file as specified in the logs, does it exist? Are the permission right?

**Comment by mindas22** [comment]
No file does not exist. I did git clone repo to plugin folder. 

maybe this file should be renamed: `roundcube_yubikey_authentication.php` to `yubikey_authentication.php`	?

**Comment by mindas22** [comment]
It seems I found out how to fix it. 

rename folder from`plugins/yubikey_authentication/` to `plugins/roundcube_yubikey_authentication/`

in file:  config/config.inc.php

change in plugins array  `yubikey_authentication` to `roundcube_yubikey_authentication`

I guess installation instruction is not correct:

`Install the code in the plugin directory and name it exactly yubikey_authentication (roundcube/plugins/yubikey_authentication/)

Add the plugin name in the plugins array of the config file (config/config.inc.php formely main.inc.php). It must match the name of the directory used in #1.

$config['plugins'] = array('yubikey_authentication');`

**Comment by northox** [comment]
True. I think it changed in one of the lastest version. I'll update the readme. Thanks for the report.
