### ISSUE TITLE
not working with rouncube 1.1.0

### ISSUE THREAD

**Issue by ib54003** [northox/roundcube-yubikey-plugin#7]
Hey the plugin doesn't seam to work Roundcube with 1.1.0.

**Comment by northox** [comment]
Hello. It's still not compatible/tested with 1.1. I'll see what I can do for you this weekend. It shouldn't be very hard to fix.

**Comment by ib54003** [comment]
Ok cool, if you need some information feel free to ask ;) thx

**Comment by ib54003** [comment]
I fixed it its working now on Roundcube 1.1.0 i fogot to create a symlink.

**Comment by northox** [comment]
a symlink to the configuration? Nice, I'll update the readme to include 1.1.

**Comment by ib54003** [comment]
I am not sure if my config is right but, i put the plugin to roundcubemail/plugins/yubikey_authentication/ but that didn't worked for me, so i checked my logs, after i created a symlink to roundcubemail/public_html/assets/plugins/yubikey_authentication/ it works, i guess my config is wrong ...
