### ISSUE TITLE
Redirect Requests (Broken)

### ISSUE THREAD

**Issue by kenetik** [northox/roundcube-yubikey-plugin#9]
After enabling on the latest roundcube and attempting to test the install, logging into the account provides a redirect loop and breaks.

**Comment by northox** [comment]
Can you describe your (versions and such)?

**Comment by northox** [comment]
Is this with version 1.1.2 of Roundcube? Any other plugin or options I should be aware of to reproduce the bug?

**Comment by northox** [comment]
@kenetik any update on this? Is it resolved or can you provide the information so I can start debugging?

**Comment by northox** [comment]
No update. I'll consider this as a false positive.
